config/routes.rb
Rails.application.routes.draw do

  resources :line_items
  resources :carts
  resources :products
  resources :notifications
  resources :orders
  resources :line_orders
  get "products/file_download/:id" => "products#file_download"
  get "/cities_by_state" => "cities#cities_by_state"
  get 'welcome/index'
  get 'welcome/aboutUs'
  get 'welcome/security'
  get 'welcome/checkout/:id' => 'welcome#checkout'
  get 'welcome/save'
  get '/my_products' => "welcome#myProducts"
  get 'welcome/pag'
  get '/user_products/:id' => 'welcome#products'
  get '/welcome/down_prod/order/:id' => 'welcome#down_prod'
  get 'my_orders' => "welcome#my_orders"
  post '/notification' => 'welcome#notification'
  get '/redirect/:id' => 'welcome#redirect'

  devise_for :users, controllers: {registrations: 'registrations'}

  root 'welcome#index'

  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: :redirect
  include CurrentCart

  def index
    @products = Product.order("id desc").page(params[:page]).per(12)
  end

  def myProducts   
    @search_query = params[:q]
    if current_user
      @products = current_user.products.search(@search_query).order('id desc').page(params[:page]).per(2)
    else
      redirect_to root_path
    end
  end

  def products
    @user = User.find(params[:id])
    @products = @user.products
  end

  def aboutUs
  end
  def security
  end
  

  def save
   @order = Order.new
   @order.user_id = current_user.id
   @order.total_price = current_cart.total_price
   @order.add_line_order_from_cart(current_cart)
   if @order.save
     current_cart.line_items.each do |i| 
      i.destroy
     end
    redirect_to "/welcome/down_prod/order/#{@order.id}"
    flash[:notice] = "Obrigado por sua compra."     
   else
    render :action => "checkout"
  end
end

def checkout
  unless current_user
    flash[:notice] = "Para finalizar sua compra você 
    precisa estar logado no sistema."
    redirect_to new_user_session_path
  else
    if current_cart.line_items.count == 0
      flash[:notice] = "Seu carrinho de compras está vazio"
      redirect_to :back
    else
      order = Order.new
      cart              = Cart.find(params[:id])
        #order           = Order.first
        #order           = Cart.find(params[:id])
        #payment         = PagSeguro::PaymentRequest.new

        order.add_line_order_from_cart(cart)
        # order.save
        payment = PagSeguro::PaymentRequest.new(email: 'doglasbatista@hotmail.com', token: '674953965F0B439DA05B70EF971F9E10')
          

        payment.reference         = order.id
        payment.notification_url  = "http://104.131.58.109:3000/notification"
        payment.redirect_url      = "http://104.131.58.109:3000/redirect/#{order}"

        order.line_order.each do |product|
          payment.items << PagSeguro::Item.new({
            id: product.product.id,
            description: product.product.title,
            amount: product.product.price.to_f,
            weight: 0
            })
        end

        #payment.items = items
        begin
          response = payment.register
        rescue
          redirect_to :back
        end
        

        if response.errors.any?
          raise response.errors.join("\n")
        else
          redirect_to response.url
        end
    end
  end
end


  def notification
    transaction = PagSeguro::Transaction.find_by_notification_code(params[:notificationCode])

    logger.info "Mahh oiii"

    if transaction.errors.empty?
      # Processa a notificação. A melhor maneira de se fazer isso é realizar
      # o processamento em background. Uma boa alternativa para isso é a
      # biblioteca Sidekiq.
    end

    render :text => "ok", status: 200
  end


  def redirect
    transaction = PagSeguro::Transaction.find_by_notification_code(params[:transaction_id])


    if transaction.errors.empty?
      # Processa a notificação. A melhor maneira de se fazer isso é realizar
      # o processamento em background. Uma boa alternativa para isso é a
      # biblioteca Sidekiq.
    end
    redirect_to welcome_save_path
  end

  def my_orders
    if current_user
      @orders = current_user.orders
    else
      redirect_to root_path
    end
  end

  def down_prod
    @order = Order.find(params[:id])
    unless current_user && current_user == @order.user
      redirect_to root_path and return
    end 
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_search.html.erb
<%= form_tag my_products_path, method: :get, class: 'search' do %>
  <%= text_field_tag :q, @search_query, class: 'search-query' , placeholder: 'Buscar por...'  %>
<% end %>

app/views/welcome/aboutUs.html.erb
<body>
  <legend>
    <font size="6">
      <p>Sobre nós</p>
    </font>
  </legend>
  <p>
    O site Pentatonic foi idealizado e desenvolvido pelo aluno Doglas Batista da Silva, estudante da Fundação Educacional do Municipio de Assis (FEMA), ex-professor de guitarra
  </p>

  <p>
    Diferente de E-Commerces como o <strong>Mercado Livre</strong> e o <strong>Bom Negócio</strong> que tem o foco na comercialização de produtos físico como computadores, roupas, etc... A Pentatonic é voltada para mídias digitais, mais especificamente vídeo aulas de guitarra, onde qualquer usuário pode produzir e comercializar seu material, tornando-o assim o site um E-Commerce interativo.
  </p>

  <p>
    O sistema tem como base a comercialização de vídeo-aulas através de um sistema de download, abolindo assim o uso de mídias físicas como DVDs ou Blu Rays. Outro ponto interessante do site é que ele presta um serviço de união, dentro da comunidade “guitarrística”.
  </p>
  <p>
    Seja bem vindo.<br/>
    Equipe PENTATONIC.
  </p>
</body>

app/views/welcome/checkout.html.erb
<%= form_for @order, :url => { :action => "save" } do |f| %>
<form>
  <fieldset>
    <legend>
      <h2>Finalizando a  compra</h2>
      Tem certeza que deseja finalizar sua compra?<br/>
    </legend>
    <button type="submit" class="btn">Finalizar</button>
  </fieldset>
</form>
<% end %>

app/views/welcome/down_prod.html.erb
<legend>
  Faça o download dos seus produtos
</legend>
<div>    
    <ul id="photo-album" style="display: block;">
      <% @order.line_order.each do |i| %>
          <li><%= link_to (image_tag i.product.cover.url(:medium)),"/products/file_download/#{i.product.id}" %>
          <%= i.product.title %>
          </li>
      <% end %>
    </ul>
    </div>

app/views/welcome/index.html.erb
<!DOCTYPE <!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="../../assets/photo.css">
</head>
<body>
<legend>
  Ultimos Lançamentos
</legend>
  <% cache ['store', Product.last] do %>
    <div>    
    <ul id="photo-album" style="display: block;">
      <% @products.each do |product| %>
        <% cache ['entry', product] do %>
          <li><%= link_to (image_tag product.cover.url(:medium)), product %><%= product.title %></li>
        <% end %>
      <% end %>
    </ul>
    </div>
  <% end %>
</body>
</html>

app/views/welcome/myProducts.html.erb
<!DOCTYPE <!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="../../assets/photo.css">
</head>
<body>
<%= render 'search' %>
  <legend>
      <h2>Meus Produtos</h2>
    </legend>
  <% cache ['store', Product.last] do %>
    <div>    
    
    <table class="table table-striped" >

      <% @products.each do |product| %>
        <% cache ['entry', product] do %>
          <tr>
            <td>
              <div class="entry">
                <div class="row">
                  <div class="col-xs-6 col-md-3">             
                    <a class="thumbnail-reponsive" style="width: 100px" <%= link_to (image_tag product.cover.url(:small)), product %>     
                    </a>
                  </div>
                </div>
              </div>
            </td>
              <td><%= link_to product.title, product %></td>
              <td><%= number_to_currency(product.price) %></td>
              <td><%= link_to product.user.nickname, "/user_products/#{product.user.id}" %></td>
              <% if belongs_to_user(product) %>
                <td>
                  <%= link_to 'Editar', edit_product_path(product), :class => 'btn btn-mini' %>
                  <%= link_to 'Deletar', product_path(product),
                              :method => :delete,
                              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Tem certeza?
                                ')) },
                              :class => 'btn btn-mini btn-danger' %>
                </td>
              <% end -%>
          </tr>     
        <% end %>
      <% end %>
    </table>
    <%= paginate @products %>
    </div>
  <% end %>
  <%= link_to 'Adicionar nova vídeo aula', new_product_path, :class => 'btn btn-primary' %>
</body>
</html>

app/views/welcome/my_orders.html.erb
<table class="table table-striped">
    <tr>
      <th>Pedido</th>
      <th>Data</th>
      <th>Link</th>
    </tr>
    <% @orders.each do |order| %>
      <tr>
      <td><%= order.id %></td>
      <td><%= order.created_at.to_date.strftime('%d/%m/%y') %></td>
      <td><%= link_to "Download", "/welcome/down_prod/order/#{order.id}"%></td>
      </tr>
    <% end %>
  </table>

app/views/welcome/products.html.erb
<body>
  <legend>
    <h2><%= @user.nickname %></h2>
    <h5><%= @user.email %></h5>
  </legend>
  
  <% cache ['store', Product.last] do %>
    <div>    
    <ul id="photo-album" style="display: block;">
      <% @products.each do |product| %>
        <% cache ['entry', product] do %>
          <li><%= link_to (image_tag product.cover.url(:medium)), product %><%= product.title %></li>      
        <% end %>
      <% end %>
    </ul>
    </div>
  <% end %>
</body>

app/views/welcome/save.html.erb
<h2>Compra finalizada</h2>
 
 Seu pedido foi realizado.

app/views/welcome/security.html.erb
<body>
  <p>
    <legend>
      <strong>Segurança</strong>
    </legend>
    A Pentatonic investe em tecnologias avançadas de proteção de dados para oferecer mais segurança a seus clientes. Nenhuma informação trafega pela rede sem ser criptografada, utilizando os melhores sistemas disponíveis no mercado.
  </p>
  <p>
    <legend>
    </legend>
    <legend>
      <strong>Dados Bancários</strong>
    </legend>
    A Pentatonic delega a instituições financeiras especializadas, o tratamento de informações de pagamento. Somente realizamos transações através de serviços de pagamentos digitais reconhecidos e comprovadamente testados.
  </p>
  <p>
    <legend>
    </legend>
  </p>
</body>