config/routes.rb
Rails.application.routes.draw do

  resources :line_items
  resources :carts
  resources :products
  resources :notifications
  resources :orders
  resources :line_orders
  get "products/file_download/:id" => "products#file_download"
  get "/cities_by_state" => "cities#cities_by_state"
  get 'welcome/index'
  get 'welcome/aboutUs'
  get 'welcome/security'
  get 'welcome/checkout/:id' => 'welcome#checkout'
  get 'welcome/save'
  get '/my_products' => "welcome#myProducts"
  get 'welcome/pag'
  get '/user_products/:id' => 'welcome#products'
  get '/welcome/down_prod/order/:id' => 'welcome#down_prod'
  get 'my_orders' => "welcome#my_orders"
  post '/notification' => 'welcome#notification'
  get '/redirect/:id' => 'welcome#redirect'

  devise_for :users, controllers: {registrations: 'registrations'}

  root 'welcome#index'

  
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity = 1
      
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    total = 0
    self.line_items.each do |a|
      total += a.product.price
    end
    total
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to welcome_index_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<ul>
  <table class="table table-striped">
    <tr>
      <th></th>
      <th>Vendedor</th>
      <th>produto</th>
      <th>valor</th>
      <th></th>
    </tr>
      <% @cart.line_items.each do |item| %> 
          <tr>
            <td>
              <ul class="thumbnails">
              <li>
                <a>
                  <%= image_tag(item.product.cover.url(:small)) %>
                </a>
              </li>
            </ul>  
            </td>
            <td><%= item.product.user.name%></td>
            <td><%= item.product.title %></td>
            <td><%= number_to_currency(item.product.price) %></td>
            <td><%= link_to 'Remover', line_item_path(item), method: :delete, :class => 'btn btn-mini'  %></td>
          </tr>        
      <% end %>
      <tr>
        <td></td>
        <td></td>
        <td>TOTAL:</td>
        <td><%= number_to_currency(@cart.total_price) %></td>
        <td><%= link_to 'Esvaziar carrinho', @cart, method: :delete, data: {confirm: 'Tem certeza?'}, :class => 'btn btn-mini'  %></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><%= link_to "Finalizar compra", "/welcome/checkout/#{@cart.id}", :class => 'btn btn-mini btn-danger ' %></td>
      </tr>
    </table>
    </br><%= link_to 'Continuar comprando', welcome_index_path, :class => 'btn btn-mini' %>
    
      </br></br>
</ul>