config/routes.rb
Rails.application.routes.draw do

  resources :line_items
  resources :carts
  resources :products
  resources :notifications
  resources :orders
  resources :line_orders
  get "products/file_download/:id" => "products#file_download"
  get "/cities_by_state" => "cities#cities_by_state"
  get 'welcome/index'
  get 'welcome/aboutUs'
  get 'welcome/security'
  get 'welcome/checkout/:id' => 'welcome#checkout'
  get 'welcome/save'
  get '/my_products' => "welcome#myProducts"
  get 'welcome/pag'
  get '/user_products/:id' => 'welcome#products'
  get '/welcome/down_prod/order/:id' => 'welcome#down_prod'
  get 'my_orders' => "welcome#my_orders"
  post '/notification' => 'welcome#notification'
  get '/redirect/:id' => 'welcome#redirect'

  devise_for :users, controllers: {registrations: 'registrations'}

  root 'welcome#index'

  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Pentatonic" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body >

    <div class="navbar navbar-fixed-top"> <!--  -->
    <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            
          </a>
          <%= link_to "Pentatonic", root_path, :class => 'brand' %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Produtos", products_path  %></li>
              <li><%= link_to "Meu Carrinho", current_cart %></li>
              <li><%= render 'products/search' %></li>
              <% if current_user %>
                <li><%= link_to "Meus Produtos", my_products_path %></li>
                <li><%= link_to "Minhas Compras", my_orders_path %></li>
                <li><%= link_to "Sair", destroy_user_session_path, method: :delete %> </li>
                <li><%= link_to "Editar Perfil", edit_user_registration_path %></li>
              <% else %>
                <li><%= link_to "Cadastre-se", new_user_registration_path %></li>
                <li><%= link_to "Fazer Login", new_user_session_path %></li>
            <% end %>
            </ul>
          </div>
          <div class="nav-collapse collapse" style="">
             
          </div>
        </div>
      </div>
    </div>    

    <div class="container">
        <div class="row">
          <div class="span9" style="margin-top: 100px;">
            <%= bootstrap_flash %>
            <% if flash[:notice] %>
              <div class="alert alert-block alert-success" ">
                <button type="button" class="close" data-dismiss="alert">&times;</button >
                <%= flash[:notice]  %>
              </div>
            <% elsif flash[:error] %>
              <div class="alert alert-block alert-error">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= flash[:error] %>
              </div>
            <% elsif flash[:alert] %>
              <div class="alert alert-block alert-danger">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <h4>Advertência!</h4>
                <%= flash[:alert] %>
              </div>
            <% end %>
            <%= yield %>
          </div>
          
        </div><!--/row-->

      <footer>
        <center>
        <p>&copy; 2014 Pentatonic Ltd</p>
        <p>
          <%=link_to "Sobre", welcome_aboutUs_path %>
          <%=link_to "Segurança", welcome_security_path %>
        </p>
        </center>
      </footer>

    </div> <!-- /container -->

  </body>
</html>